// constants.ts

import { Language } from './types';

export const NAV_LINKS = [
  { name: 'Home', path: '/' },
  { name: 'About', path: '/about' },
  { name: 'How It Works', path: '/how-it-works' },
  { name: 'Features', path: '/features' },
  { name: 'Discover Scholarships', path: '/discover' },
  { name: 'AI & Technology', path: '/ai-technology' },
  { name: 'Impact', path: '/impact' },
  { name: 'Roadmap', path: '/roadmap' },
  { name: 'Contact', path: '/contact' },
];

export const TELEGRAM_BOT_URL = 'https://web.telegram.org/k/#@SamartAI_Bot';

export const LANGUAGES: { label: string; value: Language }[] = [
  { label: 'English', value: 'en' },
  { label: 'తెలుగు (Telugu)', value: 'te' },
  { label: 'हिन्दी (Hindi)', value: 'hi' },
];

export const GEMINI_API_KEY_WARNING = `
  To enable full AI functionality, please ensure your environment has an API_KEY set.
  This application uses the Gemini API. If you encounter 'Requested entity was not found.' errors,
  it might be due to an invalid or missing API key.
  If you are using a Veo/Image generation model, please select a paid API key.
  Refer to the billing documentation: ai.google.dev/gemini-api/docs/billing
`;

export const USER_MESSAGES = {
  en: {
    heroHeadline: "SamartAI: Bridging Dreams with Opportunities",
    heroSubheadline: "Voice-powered AI for discovering government scholarships across India.",
    discoverScholarships: "Discover Scholarships",
    tryOnTelegram: "Try on Telegram",
    whatSamartAIDoes: "What SamartAI Does",
    aiScholarshipDiscovery: "AI Scholarship Discovery",
    aiScholarshipDiscoveryDesc: "Intelligent matching to government schemes based on your unique profile.",
    voiceVernacularSearch: "Voice & Vernacular Search",
    voiceVernacularSearchDesc: "Speak in English, Telugu, or Hindi. Our AI understands.",
    verifiedGovernmentSchemes: "Verified Government Schemes",
    verifiedGovernmentSchemesDesc: "Access to accurate, up-to-date data directly from government sources.",
    dualPerformanceHighlight: "Dual Performance: Web & Telegram",
    useOnWeb: "Use on Web",
    useOnWebDesc: "Rich, interactive experience with comprehensive details.",
    useOnTelegram: "Use on Telegram",
    useOnTelegramDesc: "Low-bandwidth, chat-based access for any device.",
    howItWorks: "How It Works",
    speakOrType: "1. Speak or Type in Your Language",
    speakOrTypeDesc: "Simply tell SamartAI what you're looking for.",
    aiUnderstands: "2. AI Understands Eligibility",
    aiUnderstandsDesc: "Our AI processes your intent, language, and details.",
    scholarshipsShownInstantly: "3. Scholarships Shown Instantly",
    scholarshipsShownInstantlyDesc: "Get relevant scholarship opportunities with apply links.",
    trustIndicators: "Trust & Credibility",
    poweredByAI: "Powered by Advanced AI",
    verifiedData: "Verified Government Data",
    noAds: "No Ads, No Paid Promotions",
    aboutTitle: "About SamartAI",
    aboutContent: "SamartAI is an innovative platform dedicated to empowering students, particularly those in rural and semi-urban India, by simplifying access to government scholarships. We leverage cutting-edge AI to break down language barriers and reduce the complexity of application processes. Our mission is to ensure every deserving student can find and apply for the financial aid they need to pursue their educational dreams.",
    missionStatement: "Our Mission: To democratize access to education by making scholarship discovery effortless and equitable.",
    howItWorksTitle: "How SamartAI Empowers Students",
    howItWorksIntro: "SamartAI is designed for simplicity and accessibility. Here’s a quick overview of how it works to connect you with life-changing scholarships:",
    featureSectionTitle: "Key Features That Make SamartAI Unique",
    featureVoiceInput: "Voice Input & Multilingual Support",
    featureVoiceInputDesc: "Speak naturally in English, Telugu, or Hindi. Our AI understands your queries and responds in your preferred language, making scholarship search accessible to everyone, regardless of typing proficiency.",
    featureIntentUnderstanding: "AI-Powered Intent Understanding",
    featureIntentUnderstandingDesc: "Beyond keywords, SamartAI's advanced AI brain comprehends your specific needs and eligibility criteria from conversational input, providing highly relevant scholarship matches.",
    featureVerifiedData: "Verified & Up-to-Date Schemes",
    featureVerifiedDataDesc: "We provide access to a continuously updated database of government scholarships, ensuring the information you receive is accurate, credible, and free from commercial bias or outdated details.",
    featureSimpleConversation: "Simple Conversational Search",
    featureSimpleConversationDesc: "No complex forms or filters. Interact with SamartAI as if you're talking to a knowledgeable human guide who understands the intricacies of government schemes and helps you find the right fit.",
    featureDualPlatform: "Dual Platform Accessibility",
    featureDualPlatformDesc: "Whether you prefer a rich, interactive web interface or a low-bandwidth, chat-based experience on Telegram, SamartAI offers consistent, powerful AI assistance tailored to your environment.",
    aiTechTitle: "The Intelligence Behind SamartAI",
    aiTechIntro: "SamartAI is built on a foundation of advanced AI and natural language processing to deliver its unique conversational scholarship discovery experience. Here’s a glimpse into the technology that powers our platform:",
    aiTechNLPLM: "Natural Language Processing (NLP) & Large Language Models (LLMs)",
    aiTechNLPLMDesc: "At the core of SamartAI, sophisticated NLP techniques and powerful LLMs enable the platform to understand complex queries, extract crucial eligibility information, and generate human-like responses across multiple languages.",
    aiTechVoiceRecognition: "Multilingual Speech-to-Text (STT) & Text-to-Speech (TTS)",
    aiTechVoiceRecognitionDesc: "We integrate state-of-the-art STT to accurately transcribe spoken inputs in English, Telugu, and Hindi, and TTS to provide clear, friendly audio responses, facilitating a truly voice-first interaction.",
    aiTechDataIntegration: "Secure Data Integration & Matching Algorithms",
    aiTechDataIntegrationDesc: "Our system securely integrates with verified government scholarship databases. Proprietary matching algorithms then intelligently cross-reference user profiles (derived from conversations) with scholarship criteria to suggest the most relevant opportunities.",
    aiTechScalability: "Scalable & Robust Architecture",
    aiTechScalabilityDesc: "Designed for enterprise-grade performance, SamartAI's backend is built to handle high volumes of concurrent users and data, ensuring reliable and fast access to information, even in low-connectivity areas.",
    impactTitle: "Our Impact: Empowering Education, Transforming Lives",
    impactIntro: "SamartAI is more than just a platform; it's a movement to unlock educational opportunities for millions. We are committed to creating tangible social impact, especially for underserved communities.",
    impactRuralStudents: "Empowering Rural & Semi-Urban Students",
    impactRuralStudentsDesc: "By removing barriers of language and digital literacy, SamartAI helps students from remote areas access scholarships they might never have known about, bridging the urban-rural opportunity gap.",
    impactParentsVolunteers: "Support for Parents & College Help-Desks",
    impactParentsVolunteersDesc: "Parents with limited English or technical skills can easily navigate scholarship searches, while college help-desk volunteers can efficiently guide numerous students, multiplying their impact.",
    impactCaseStudy1Title: "Case Study: Lakshmi's Journey",
    impactCaseStudy1Desc: "Lakshmi, a bright student from a small village in Andhra Pradesh, struggled to find scholarships due to language barriers and limited internet access. Using SamartAI on Telegram, her father spoke in Telugu about her academic achievements and financial situation. Within minutes, SamartAI suggested three relevant state and national scholarships. Lakshmi successfully applied for one, securing funding for her engineering degree.",
    roadmapTitle: "Future Roadmap: Innovating for Tomorrow's Learners",
    roadmapIntro: "Our journey to empower students is continuous. SamartAI is constantly evolving, with exciting features and expansions planned for the future:",
    roadmapWhatsApp: "WhatsApp Integration",
    roadmapWhatsAppDesc: "Expanding our messaging platform presence to include WhatsApp, reaching an even wider audience with seamless, chat-based scholarship discovery.",
    roadmapOCR: "OCR Document Scanning",
    roadmapOCRDesc: "Simplifying the application process further by allowing users to scan and upload documents, with AI extracting relevant information for eligibility pre-checks.",
    roadmapVoiceOnly: "Enhanced Voice-Only Mode",
    roadmapVoiceOnlyDesc: "Developing a fully voice-driven experience for users who prefer minimal visual interaction, making the platform even more accessible.",
    roadmapLowBandwidth: "Optimized Low-Bandwidth Usage",
    roadmapLowBandwidthDesc: "Continuous improvements to ensure SamartAI remains highly functional and responsive even on slow or intermittent internet connections, crucial for rural users.",
    roadmapMoreLanguages: "Expanded Language Support",
    roadmapMoreLanguagesDesc: "Introducing support for more regional Indian languages to make SamartAI accessible to an even broader and diverse student population.",
    contactTitle: "Contact Us & Get Involved",
    contactIntro: "Have questions, feedback, or want to partner with SamartAI? We'd love to hear from you!",
    contactEmail: "Email Us",
    contactPartnerships: "Partnerships & Collaborations",
    contactFeedback: "Feedback & Support",
    contactJoinUs: "Join Our Mission",
    contactJoinUsDesc: "If you're passionate about leveraging AI for social good, we're always looking for talented individuals and organizations to join us. Reach out!",
    chatPlaceholder: "Speak or type your scholarship query...",
    exampleQueries: "Example queries:",
    exampleQuery1: "Scholarships for engineering students.",
    exampleQuery2: "Scholarships for girls from low-income families.",
    exampleQuery3: "Eligibility for SC/ST scholarships.",
    microphoneListen: "Listening...",
    microphoneTapToSpeak: "Tap to Speak",
    microphoneProcessing: "Processing...",
    scholarshipName: "Scheme Name",
    category: "Category",
    incomeLimit: "Income Limit",
    description: "Description",
    applyNow: "Apply Now",
    loadingScholarships: "Finding scholarships...",
    noScholarshipsFound: "No scholarships found based on your query. Please try rephrasing or providing more details.",
    errorOccurred: "An error occurred. Please try again.",
    aiThinking: "SamartAI is thinking...",
    speechRecognitionError: "Speech recognition error. Please try again.",
    noSpeechDetected: "No speech detected. Please try again.",
  },
  te: {
    heroHeadline: "సమర్థ్‌ఏఐ: కలలు, అవకాశాల వారధి",
    heroSubheadline: "భారతదేశం అంతటా ప్రభుత్వ స్కాలర్‌షిప్‌లను కనుగొనడానికి వాయిస్ ఆధారిత AI.",
    discoverScholarships: "స్కాలర్‌షిప్‌లను కనుగొనండి",
    tryOnTelegram: "టెలిగ్రామ్‌లో ప్రయత్నించండి",
    whatSamartAIDoes: "సమర్థ్‌ఏఐ ఏమి చేస్తుంది",
    aiScholarshipDiscovery: "AI స్కాలర్‌షిప్ డిస్కవరీ",
    aiScholarshipDiscoveryDesc: "మీ ప్రత్యేక ప్రొఫైల్ ఆధారంగా ప్రభుత్వ పథకాలకు తెలివైన సరిపోలిక.",
    voiceVernacularSearch: "వాయిస్ & స్థానిక భాషా శోధన",
    voiceVernacularSearchDesc: "ఇంగ్లీష్, తెలుగు లేదా హిందీలో మాట్లాడండి. మా AI అర్థం చేసుకుంటుంది.",
    verifiedGovernmentSchemes: "ధృవీకరించబడిన ప్రభుత్వ పథకాలు",
    verifiedGovernmentSchemesDesc: "ప్రభుత్వ వనరుల నుండి నేరుగా ఖచ్చితమైన, నవీనమైన డేటాకు యాక్సెస్.",
    dualPerformanceHighlight: "ద్వంద్వ పనితీరు: వెబ్ & టెలిగ్రామ్",
    useOnWeb: "వెబ్‌లో ఉపయోగించండి",
    useOnWebDesc: "సమగ్ర వివరాలతో గొప్ప, ఇంటరాక్టివ్ అనుభవం.",
    useOnTelegram: "టెలిగ్రామ్‌లో ఉపయోగించండి",
    useOnTelegramDesc: "ఏదైనా పరికరం కోసం తక్కువ-బ్యాండ్‌విడ్త్, చాట్ ఆధారిత యాక్సెస్.",
    howItWorks: "ఇది ఎలా పని చేస్తుంది",
    speakOrType: "1. మీ భాషలో మాట్లాడండి లేదా టైప్ చేయండి",
    speakOrTypeDesc: "మీరు ఏమి వెతుకుతున్నారో సమర్థ్‌ఏఐకి చెప్పండి.",
    aiUnderstands: "2. AI అర్హతను అర్థం చేసుకుంటుంది",
    aiUnderstandsDesc: "మా AI మీ ఉద్దేశం, భాష మరియు వివరాలను ప్రాసెస్ చేస్తుంది.",
    scholarshipsShownInstantly: "3. స్కాలర్‌షిప్‌లు తక్షణమే చూపబడతాయి",
    scholarshipsShownInstantlyDesc: "అవసరమైన స్కాలర్‌షిప్ అవకాశాలను వర్తించు లింక్‌లతో పొందండి.",
    trustIndicators: "విశ్వసనీయత & విశ్వసనీయత",
    poweredByAI: "అధునాతన AI ద్వారా ఆధారితం",
    verifiedData: "ధృవీకరించబడిన ప్రభుత్వ డేటా",
    noAds: "ప్రకటనలు లేవు, పెయిడ్ ప్రమోషన్లు లేవు",
    aboutTitle: "సమర్థ్‌ఏఐ గురించి",
    aboutContent: "సమర్థ్‌ఏఐ అనేది విద్యార్థులకు, ముఖ్యంగా గ్రామీణ మరియు సెమీ-అర్బన్ భారతదేశంలో ఉన్నవారికి, ప్రభుత్వ స్కాలర్‌షిప్‌లకు ప్రాప్యతను సరళీకృతం చేయడం ద్వారా సాధికారత కల్పించడానికి అంకితం చేయబడిన ఒక వినూత్న వేదిక. భాషా అడ్డంకులను తొలగించడానికి మరియు దరఖాస్తు ప్రక్రియల సంక్లిష్టతను తగ్గించడానికి మేము అత్యాధునిక AIని ఉపయోగిస్తాము. ప్రతి అర్హత గల విద్యార్థి తమ విద్యా కలలను కొనసాగించడానికి అవసరమైన ఆర్థిక సహాయాన్ని కనుగొని దరఖాస్తు చేసుకోగలరని నిర్ధారించడం మా లక్ష్యం.",
    missionStatement: "మా లక్ష్యం: స్కాలర్‌షిప్ డిస్కవరీని సులభతరం చేయడం మరియు సమానత్వం చేయడం ద్వారా విద్యకు ప్రాప్యతను ప్రజాస్వామ్యం చేయడం.",
    howItWorksTitle: "సమర్థ్‌ఏఐ విద్యార్థులకు ఎలా సాధికారత కల్పిస్తుంది",
    howItWorksIntro: "సమర్థ్‌ఏఐ సరళత మరియు ప్రాప్యత కోసం రూపొందించబడింది. మీ జీవితాన్ని మార్చే స్కాలర్‌షిప్‌లతో మిమ్మల్ని కనెక్ట్ చేయడానికి ఇది ఎలా పని చేస్తుందో ఇక్కడ ఒక సంక్షిప్త అవలోకనం ఉంది:",
    featureSectionTitle: "సమర్థ్‌ఏఐని ప్రత్యేకంగా చేసే ముఖ్య లక్షణాలు",
    featureVoiceInput: "వాయిస్ ఇన్‌పుట్ & బహుభాషా మద్దతు",
    featureVoiceInputDesc: "ఇంగ్లీష్, తెలుగు లేదా హిందీలో సహజంగా మాట్లాడండి. మా AI మీ ప్రశ్నలను అర్థం చేసుకుంటుంది మరియు మీకు నచ్చిన భాషలో ప్రతిస్పందిస్తుంది, టైపింగ్ నైపుణ్యంతో సంబంధం లేకుండా ప్రతి ఒక్కరికీ స్కాలర్‌షిప్ శోధనను అందుబాటులోకి తెస్తుంది.",
    featureIntentUnderstanding: "AI-ఆధారిత ఉద్దేశ్య అవగాహన",
    featureIntentUnderstandingDesc: "కీలకపదాలకు మించి, సమర్థ్‌ఏఐ యొక్క అధునాతన AI మెదడు సంభాషణాత్మక ఇన్‌పుట్ నుండి మీ నిర్దిష్ట అవసరాలు మరియు అర్హత ప్రమాణాలను గ్రహిస్తుంది, అత్యంత సంబంధిత స్కాలర్‌షిప్ సరిపోలికలను అందిస్తుంది.",
    featureVerifiedData: "ధృవీకరించబడిన & నవీనమైన పథకాలు",
    featureVerifiedDataDesc: "ప్రభుత్వ స్కాలర్‌షిప్‌ల యొక్క నిరంతరం నవీనమైన డేటాబేస్‌కు మేము ప్రాప్యతను అందిస్తాము, మీరు అందుకున్న సమాచారం ఖచ్చితమైనది, విశ్వసనీయమైనది మరియు వాణిజ్య పక్షపాతం లేదా పాత వివరాలు లేనిది.",
    featureSimpleConversation: "సాధారణ సంభాషణాత్మక శోధన",
    featureSimpleConversationDesc: "సంక్లిష్టమైన ఫారమ్‌లు లేదా ఫిల్టర్‌లు లేవు. ప్రభుత్వ పథకాలలోని చిక్కులను అర్థం చేసుకున్న మరియు మీకు సరైన సరిపోలికను కనుగొనడంలో సహాయపడే జ్ఞానవంతమైన మానవ గైడ్‌తో మాట్లాడుతున్నట్లుగా సమర్థ్‌ఏఐతో సంభాషించండి.",
    featureDualPlatform: "ద్వంద్వ ప్లాట్‌ఫారమ్ ప్రాప్యత",
    featureDualPlatformDesc: "మీరు గొప్ప, ఇంటరాక్టివ్ వెబ్ ఇంటర్‌ఫేస్‌ను లేదా తక్కువ-బ్యాండ్‌విడ్త్, టెలిగ్రామ్‌లో చాట్ ఆధారిత అనుభవాన్ని ఇష్టపడినా, సమర్థ్‌ఏఐ మీ పర్యావరణానికి అనుగుణంగా స్థిరమైన, శక్తివంతమైన AI సహాయాన్ని అందిస్తుంది.",
    aiTechTitle: "సమర్థ్‌ఏఐ వెనుక మేధస్సు",
    aiTechIntro: "సమర్థ్‌ఏఐ తన ప్రత్యేక సంభాషణాత్మక స్కాలర్‌షిప్ డిస్కవరీ అనుభవాన్ని అందించడానికి అధునాతన AI మరియు సహజ భాషా ప్రాసెసింగ్ పునాదిపై నిర్మించబడింది. మా ప్లాట్‌ఫారమ్‌కు శక్తినిచ్చే సాంకేతికత గురించి ఇక్కడ ఒక సంగ్రహావలోకనం ఉంది:",
    aiTechNLPLM: "సహజ భాషా ప్రాసెసింగ్ (NLP) & పెద్ద భాషా నమూనాలు (LLMs)",
    aiTechNLPLMDesc: "సమర్థ్‌ఏఐ యొక్క ప్రధాన భాగంలో, అధునాతన NLP పద్ధతులు మరియు శక్తివంతమైన LLMలు సంక్లిష్ట ప్రశ్నలను అర్థం చేసుకోవడానికి, కీలక అర్హత సమాచారాన్ని సంగ్రహించడానికి మరియు బహుళ భాషలలో మానవ-వంటి ప్రతిస్పందనలను రూపొందించడానికి ప్లాట్‌ఫారమ్‌ను అనుమతిస్తాయి.",
    aiTechVoiceRecognition: "బహుభాషా స్పీచ్-టు-టెక్స్ట్ (STT) & టెక్స్ట్-టు-స్పీచ్ (TTS)",
    aiTechVoiceRecognitionDesc: "ఇంగ్లీష్, తెలుగు మరియు హిందీలో మాట్లాడిన ఇన్‌పుట్‌లను ఖచ్చితంగా లిప్యంతరీకరించడానికి మరియు స్పష్టమైన, స్నేహపూర్వక ఆడియో ప్రతిస్పందనలను అందించడానికి మేము అత్యాధునిక STTని అనుసంధానిస్తాము, నిజంగా వాయిస్-ఫస్ట్ ఇంటరాక్షన్‌ను సులభతరం చేస్తాము.",
    aiTechDataIntegration: "సురక్షిత డేటా ఇంటిగ్రేషన్ & సరిపోలే అల్గోరిథమ్‌లు",
    aiTechDataIntegrationDesc: "మా సిస్టమ్ ధృవీకరించబడిన ప్రభుత్వ స్కాలర్‌షిప్ డేటాబేస్‌లతో సురక్షితంగా అనుసంధానిస్తుంది. యాజమాన్య సరిపోలే అల్గోరిథమ్‌లు అప్పుడు తెలివిగా వినియోగదారు ప్రొఫైల్‌లను (సంభాషణల నుండి తీసుకోబడినవి) స్కాలర్‌షిప్ ప్రమాణాలతో క్రాస్-రిఫరెన్స్ చేస్తాయి, అత్యంత సంబంధిత అవకాశాలను సూచించడానికి.",
    aiTechScalability: "స్కేలబుల్ & దృఢమైన ఆర్కిటెక్చర్",
    aiTechScalabilityDesc: "ఎంటర్‌ప్రైజ్-గ్రేడ్ పనితీరు కోసం రూపొందించబడిన సమర్థ్‌ఏఐ యొక్క బ్యాకెండ్ అధిక సంఖ్యలో ఏకకాల వినియోగదారులను మరియు డేటాను నిర్వహించడానికి నిర్మించబడింది, తక్కువ-కనెక్టివిటీ ప్రాంతాలలో కూడా సమాచారానికి నమ్మకమైన మరియు వేగవంతమైన ప్రాప్యతను నిర్ధారిస్తుంది.",
    impactTitle: "మా ప్రభావం: విద్యను సాధికారత చేయడం, జీవితాలను మార్చడం",
    impactIntro: "సమర్థ్‌ఏఐ కేవలం ఒక వేదిక కంటే ఎక్కువ; ఇది మిలియన్ల మందికి విద్యా అవకాశాలను అన్‌లాక్ చేయడానికి ఒక ఉద్యమం. మేము స్పష్టమైన సామాజిక ప్రభావాన్ని సృష్టించడానికి కట్టుబడి ఉన్నాము, ముఖ్యంగా తక్కువ సేవలు పొందిన వర్గాల కోసం.",
    impactRuralStudents: "గ్రామీణ & సెమీ-అర్బన్ విద్యార్థులకు సాధికారత",
    impactRuralStudentsDesc: "భాష మరియు డిజిటల్ అక్షరాస్యత యొక్క అడ్డంకులను తొలగించడం ద్వారా, సమర్థ్‌ఏఐ మారుమూల ప్రాంతాల విద్యార్థులు వారికి ఎప్పటికీ తెలియని స్కాలర్‌షిప్‌లను యాక్సెస్ చేయడానికి సహాయపడుతుంది, పట్టణ-గ్రామీణ అవకాశాల అంతరాన్ని తగ్గిస్తుంది.",
    impactParentsVolunteers: "తల్లిదండ్రులు & కళాశాల హెల్ప్-డెస్క్‌ల కోసం మద్దతు",
    impactParentsVolunteersDesc: "తక్కువ ఇంగ్లీష్ లేదా సాంకేతిక నైపుణ్యాలు ఉన్న తల్లిదండ్రులు స్కాలర్‌షిప్ శోధనలను సులభంగా నావిగేట్ చేయగలరు, అయితే కళాశాల హెల్ప్-డెస్క్ వాలంటీర్లు అనేక మంది విద్యార్థులకు సమర్థవంతంగా మార్గనిర్దేశం చేయగలరు, వారి ప్రభావాన్ని గుణించడం.",
    impactCaseStudy1Title: "కేస్ స్టడీ: లక్ష్మి ప్రయాణం",
    impactCaseStudy1Desc: "ఆంధ్రప్రదేశ్‌లోని ఒక చిన్న గ్రామానికి చెందిన ప్రకాశవంతమైన విద్యార్థిని లక్ష్మి, భాషా అడ్డంకులు మరియు పరిమిత ఇంటర్నెట్ ప్రాప్యత కారణంగా స్కాలర్‌షిప్‌లను కనుగొనడానికి కష్టపడింది. టెలిగ్రామ్‌లో సమర్థ్‌ఏఐని ఉపయోగించి, ఆమె తండ్రి ఆమె విద్యా విజయాలు మరియు ఆర్థిక పరిస్థితి గురించి తెలుగులో మాట్లాడారు. నిమిషాల్లో, సమర్థ్‌ఏఐ మూడు సంబంధిత రాష్ట్ర మరియు జాతీయ స్కాలర్‌షిప్‌లను సూచించింది. లక్ష్మి ఒకదానికి విజయవంతంగా దరఖాస్తు చేసుకుంది, తన ఇంజనీరింగ్ డిగ్రీ కోసం నిధులు పొందింది.",
    roadmapTitle: "భవిష్యత్ రోడ్‌మ్యాప్: రేపటి అభ్యాసకుల కోసం ఆవిష్కరణ",
    roadmapIntro: "విద్యార్థులకు సాధికారత కల్పించాలనే మా ప్రయాణం నిరంతరాయంగా కొనసాగుతోంది. సమర్థ్‌ఏఐ నిరంతరం అభివృద్ధి చెందుతోంది, భవిష్యత్తు కోసం అద్భుతమైన ఫీచర్లు మరియు విస్తరణలు ప్రణాళిక చేయబడ్డాయి:",
    roadmapWhatsApp: "వాట్సాప్ ఇంటిగ్రేషన్",
    roadmapWhatsAppDesc: "వాట్సాప్‌ను చేర్చడానికి మా మెసేజింగ్ ప్లాట్‌ఫారమ్ ఉనికిని విస్తరిస్తోంది, అంతరాయం లేని, చాట్ ఆధారిత స్కాలర్‌షిప్ డిస్కవరీతో మరింత విస్తృత ప్రేక్షకులను చేరుకుంటుంది.",
    roadmapOCR: "OCR డాక్యుమెంట్ స్కానింగ్",
    roadmapOCRDesc: "అర్హత ముందస్తు తనిఖీల కోసం AI సంబంధిత సమాచారాన్ని సంగ్రహించడంతో, వినియోగదారులు పత్రాలను స్కాన్ చేసి అప్‌లోడ్ చేయడానికి అనుమతించడం ద్వారా దరఖాస్తు ప్రక్రియను మరింత సరళీకృతం చేస్తుంది.",
    roadmapVoiceOnly: "మెరుగుపరచబడిన వాయిస్-ఓన్లీ మోడ్",
    roadmapVoiceOnlyDesc: "కనీస దృశ్య పరస్పర చర్యను ఇష్టపడే వినియోగదారుల కోసం పూర్తిగా వాయిస్ ఆధారిత అనుభవాన్ని అభివృద్ధి చేస్తుంది, ప్లాట్‌ఫారమ్‌ను మరింత అందుబాటులోకి తెస్తుంది.",
    roadmapLowBandwidth: "ఆప్టిమైజ్ చేయబడిన తక్కువ-బ్యాండ్‌విడ్త్ వినియోగం",
    roadmapLowBandwidthDesc: "తక్కువ లేదా అంతరాయం ఉన్న ఇంటర్నెట్ కనెక్షన్‌లలో కూడా సమర్థ్‌ఏఐ అత్యంత క్రియాత్మకంగా మరియు ప్రతిస్పందించేలా ఉండేలా నిరంతర మెరుగుదలలు, గ్రామీణ వినియోగదారులకు కీలకమైనది.",
    roadmapMoreLanguages: "విస్తరించిన భాషా మద్దతు",
    roadmapMoreLanguagesDesc: "మరింత విస్తృత మరియు విభిన్న విద్యార్థి జనాభాకు సమర్థ్‌ఏఐని అందుబాటులోకి తీసుకురావడానికి మరిన్ని ప్రాంతీయ భారతీయ భాషలకు మద్దతును పరిచయం చేస్తుంది.",
    contactTitle: "మమ్మల్ని సంప్రదించండి & పాల్గొనండి",
    contactIntro: "ప్రశ్నలు, అభిప్రాయాలు ఉన్నాయా లేదా సమర్థ్‌ఏఐతో భాగస్వామ్యం కావాలనుకుంటున్నారా? మీ నుండి వినడానికి మేము ఇష్టపడతాము!",
    contactEmail: "మాకు ఇమెయిల్ చేయండి",
    contactPartnerships: "భాగస్వామ్యాలు & సహకారాలు",
    contactFeedback: "అభిప్రాయం & మద్దతు",
    contactJoinUs: "మా మిషన్‌లో చేరండి",
    contactJoinUsDesc: "మీరు సామాజిక ప్రయోజనం కోసం AIని ఉపయోగించడంలో ఆసక్తి కలిగి ఉంటే, మాతో చేరడానికి మేము ఎల్లప్పుడూ ప్రతిభావంతులైన వ్యక్తులు మరియు సంస్థల కోసం చూస్తున్నాము. చేరుకోండి!",
    chatPlaceholder: "మీ స్కాలర్‌షిప్ ప్రశ్నను మాట్లాడండి లేదా టైప్ చేయండి...",
    exampleQueries: "ఉదాహరణ ప్రశ్నలు:",
    exampleQuery1: "ఇంజనీరింగ్ విద్యార్థుల కోసం స్కాలర్‌షిప్‌లు.",
    exampleQuery2: "తక్కువ ఆదాయ కుటుంబాల నుండి బాలికల కోసం స్కాలర్‌షిప్‌లు.",
    exampleQuery3: "SC/ST స్కాలర్‌షిప్‌లకు అర్హత.",
    microphoneListen: "వినడం...",
    microphoneTapToSpeak: "మాట్లాడటానికి నొక్కండి",
    microphoneProcessing: "ప్రాసెస్ చేస్తోంది...",
    scholarshipName: "పథకం పేరు",
    category: "వర్గం",
    incomeLimit: "ఆదాయ పరిమితి",
    description: "వివరణ",
    applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
    loadingScholarships: "స్కాలర్‌షిప్‌లను కనుగొంటున్నాము...",
    noScholarshipsFound: "మీ ప్రశ్న ఆధారంగా స్కాలర్‌షిప్‌లు కనుగొనబడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి లేదా మరిన్ని వివరాలను అందించండి.",
    errorOccurred: "ఒక లోపం సంభవించింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    aiThinking: "సమర్థ్‌ఏఐ ఆలోచిస్తోంది...",
    speechRecognitionError: "స్పీచ్ రికగ్నిషన్ లోపం. దయచేసి మళ్లీ ప్రయత్నించండి.",
    noSpeechDetected: "మాట గుర్తించబడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.",
  },
  hi: {
    heroHeadline: "समर्थएआई: सपनों को अवसरों से जोड़ना",
    heroSubheadline: "पूरे भारत में सरकारी छात्रवृत्तियाँ खोजने के लिए वॉयस-पावर्ड एआई।",
    discoverScholarships: "छात्रवृत्तियाँ खोजें",
    tryOnTelegram: "टेलीग्राम पर आज़माएँ",
    whatSamartAIDoes: "समर्थएआई क्या करता है",
    aiScholarshipDiscovery: "एआई छात्रवृत्ति खोज",
    aiScholarshipDiscoveryDesc: "आपकी अनूठी प्रोफ़ाइल के आधार पर सरकारी योजनाओं से इंटेलिजेंट मिलान।",
    voiceVernacularSearch: "वॉयस और स्थानीय भाषा खोज",
    voiceVernacularSearchDesc: "अंग्रेजी, तेलुगु या हिंदी में बोलें। हमारा एआई समझता है।",
    verifiedGovernmentSchemes: "सत्यापित सरकारी योजनाएँ",
    verifiedGovernmentSchemesDesc: "सरकारी स्रोतों से सीधे सटीक, अद्यतन डेटा तक पहुँच।",
    dualPerformanceHighlight: "दोहरी प्रदर्शन: वेब और टेलीग्राम",
    useOnWeb: "वेब पर उपयोग करें",
    useOnWebDesc: "व्यापक विवरण के साथ समृद्ध, इंटरैक्टिव अनुभव।",
    useOnTelegram: "टेलीग्राम पर उपयोग करें",
    useOnTelegramDesc: "किसी भी डिवाइस के लिए कम-बैंडविड्थ, चैट-आधारित पहुँच।",
    howItWorks: "यह कैसे काम करता है",
    speakOrType: "1. अपनी भाषा में बोलें या टाइप करें",
    speakOrTypeDesc: "बस समर्थएआई को बताएं कि आप क्या खोज रहे हैं।",
    aiUnderstands: "2. एआई पात्रता को समझता है",
    aiUnderstandsDesc: "हमारा एआई आपके इरादे, भाषा और विवरण को संसाधित करता है।",
    scholarshipsShownInstantly: "3. छात्रवृत्तियाँ तुरंत दिखेंगी",
    scholarshipsShownInstantlyDesc: "आवेदन लिंक के साथ प्रासंगिक छात्रवृत्ति के अवसर प्राप्त करें।",
    trustIndicators: "विश्वास और विश्वसनीयता",
    poweredByAI: "उन्नत एआई द्वारा संचालित",
    verifiedData: "सत्यापित सरकारी डेटा",
    noAds: "कोई विज्ञापन नहीं, कोई सशुल्क प्रचार नहीं",
    aboutTitle: "समर्थएआई के बारे में",
    aboutContent: "समर्थएआई एक अभिनव मंच है जो छात्रों, विशेष रूप से ग्रामीण और अर्ध-शहरी भारत में रहने वाले छात्रों को सरकारी छात्रवृत्तियों तक पहुँच को सरल बनाकर सशक्त बनाने के लिए समर्पित है। हम भाषा की बाधाओं को तोड़ने और आवेदन प्रक्रियाओं की जटिलता को कम करने के लिए अत्याधुनिक एआई का लाभ उठाते हैं। हमारा मिशन यह सुनिश्चित करना है कि हर योग्य छात्र अपनी शैक्षिक आकांक्षाओं को पूरा करने के लिए आवश्यक वित्तीय सहायता प्राप्त कर सके और उसके लिए आवेदन कर सके।",
    missionStatement: "हमारा मिशन: छात्रवृत्ति खोज को सहज और न्यायसंगत बनाकर शिक्षा तक पहुँच का लोकतंत्रीकरण करना।",
    howItWorksTitle: "समर्थएआई छात्रों को कैसे सशक्त बनाता है",
    howItWorksIntro: "समर्थएआई को सरलता और पहुंच के लिए डिज़ाइन किया गया है। जीवन बदलने वाली छात्रवृत्तियों से आपको जोड़ने के लिए यह कैसे काम करता है, इसका एक संक्षिप्त अवलोकन यहां दिया गया है:",
    featureSectionTitle: "प्रमुख विशेषताएँ जो समर्थएआई को अद्वितीय बनाती हैं",
    featureVoiceInput: "वॉयस इनपुट और बहुभाषी समर्थन",
    featureVoiceInputDesc: "अंग्रेजी, तेलुगु या हिंदी में स्वाभाविक रूप से बोलें। हमारा एआई आपकी प्रश्नों को समझता है और आपकी पसंदीदा भाषा में जवाब देता है, जिससे टाइपिंग दक्षता की परवाह किए बिना सभी के लिए छात्रवृत्ति खोज सुलभ हो जाती है।",
    featureIntentUnderstanding: "एआई-संचालित इरादे की समझ",
    featureIntentUnderstandingDesc: "कीवर्ड से परे, समर्थएआई का उन्नत एआई मस्तिष्क संवादात्मक इनपुट से आपकी विशिष्ट आवश्यकताओं और पात्रता मानदंडों को समझता है, जिससे अत्यधिक प्रासंगिक छात्रवृत्ति मिलान प्रदान होता है।",
    featureVerifiedData: "सत्यापित और अद्यतन योजनाएँ",
    featureVerifiedDataDesc: "हम सरकारी छात्रवृत्तियों के लगातार अद्यतन डेटाबेस तक पहुँच प्रदान करते हैं, यह सुनिश्चित करते हुए कि आपको प्राप्त जानकारी सटीक, विश्वसनीय और वाणिज्यिक पूर्वाग्रह या पुरानी जानकारी से मुक्त हो।",
    featureSimpleConversation: "सरल संवादात्मक खोज",
    featureSimpleConversationDesc: "कोई जटिल फ़ॉर्म या फ़िल्टर नहीं। समर्थएआई के साथ ऐसे बातचीत करें जैसे आप किसी जानकार मानव मार्गदर्शक से बात कर रहे हों जो सरकारी योजनाओं की बारीकियों को समझता है और आपको सही विकल्प खोजने में मदद करता है।",
    featureDualPlatform: "दोहरी प्लेटफ़ॉर्म पहुंच",
    featureDualPlatformDesc: "चाहे आप एक समृद्ध, इंटरैक्टिव वेब इंटरफ़ेस पसंद करते हों या टेलीग्राम पर कम-बैंडविड्थ, चैट-आधारित अनुभव, समर्थएआई आपके वातावरण के अनुरूप लगातार, शक्तिशाली एआई सहायता प्रदान करता है।",
    aiTechTitle: "समर्थएआई के पीछे की बुद्धिमत्ता",
    aiTechIntro: "समर्थएआई अपने अद्वितीय संवादात्मक छात्रवृत्ति खोज अनुभव प्रदान करने के लिए उन्नत एआई और प्राकृतिक भाषा प्रसंस्करण की नींव पर बनाया गया है। यहां उस तकनीक की एक झलक दी गई है जो हमारे मंच को शक्ति प्रदान करती है:",
    aiTechNLPLM: "प्राकृतिक भाषा प्रसंस्करण (एनएलपी) और बड़े भाषा मॉडल (एलएलएम)",
    aiTechNLPLMDesc: "समर्थएआई के मूल में, परिष्कृत एनएलपी तकनीकें और शक्तिशाली एलएलएम मंच को जटिल प्रश्नों को समझने, महत्वपूर्ण पात्रता जानकारी निकालने और कई भाषाओं में मानव-जैसी प्रतिक्रियाएँ उत्पन्न करने में सक्षम बनाते हैं।",
    aiTechVoiceRecognition: "बहुभाषी स्पीच-टू-टेक्स्ट (एसटीटी) और टेक्स्ट-टू-स्पीच (टीटीएस)",
    aiTechVoiceRecognitionDesc: "हम अंग्रेजी, तेलुगु और हिंदी में बोले गए इनपुट को सटीक रूप से ट्रांसक्रिप्ट करने के लिए अत्याधुनिक एसटीटी को एकीकृत करते हैं, और स्पष्ट, मैत्रीपूर्ण ऑडियो प्रतिक्रियाएं प्रदान करने के लिए टीटीएस को एकीकृत करते हैं, जिससे वास्तव में वॉयस-फर्स्ट इंटरैक्शन की सुविधा मिलती है।",
    aiTechDataIntegration: "सुरक्षित डेटा एकीकरण और मिलान एल्गोरिदम",
    aiTechDataIntegrationDesc: "हमारा सिस्टम सत्यापित सरकारी छात्रवृत्ति डेटाबेस के साथ सुरक्षित रूप से एकीकृत होता है। मालिकाना मिलान एल्गोरिदम तब उपयोगकर्ता प्रोफाइल (बातचीत से प्राप्त) को छात्रवृत्ति मानदंडों के साथ बुद्धिमानी से क्रॉस-रेफरेंस करते हैं ताकि सबसे प्रासंगिक अवसरों का सुझाव दिया जा सके।",
    aiTechScalability: "स्केलेबल और मजबूत वास्तुकला",
    aiTechScalabilityDesc: "एंटरप्राइज़-ग्रेड प्रदर्शन के लिए डिज़ाइन किया गया, समर्थएआई का बैकएंड बड़ी संख्या में समवर्ती उपयोगकर्ताओं और डेटा को संभालने के लिए बनाया गया है, जिससे कम-कनेक्टिविटी वाले क्षेत्रों में भी जानकारी तक विश्वसनीय और तेज़ पहुँच सुनिश्चित होती है।",
    impactTitle: "हमारा प्रभाव: शिक्षा को सशक्त बनाना, जीवन बदलना",
    impactIntro: "समर्थएआई सिर्फ एक मंच से कहीं अधिक है; यह लाखों लोगों के लिए शैक्षिक अवसरों को अनलॉक करने का एक आंदोलन है। हम ठोस सामाजिक प्रभाव बनाने के लिए प्रतिबद्ध हैं, खासकर वंचित समुदायों के लिए।",
    impactRuralStudents: "ग्रामीण और अर्ध-शहरी छात्रों को सशक्त बनाना",
    impactRuralStudentsDesc: "भाषा और डिजिटल साक्षरता की बाधाओं को दूर करके, समर्थएआई दूरदराज के क्षेत्रों के छात्रों को उन छात्रवृत्तियों तक पहुँचने में मदद करता है जिनके बारे में उन्हें कभी पता नहीं होता, शहरी-ग्रामीण अवसर के अंतर को पाटता है।",
    impactParentsVolunteers: "माता-पिता और कॉलेज हेल्प-डेस्क के लिए समर्थन",
    impactParentsVolunteersDesc: "सीमित अंग्रेजी या तकनीकी कौशल वाले माता-पिता आसानी से छात्रवृत्ति खोज को नेविगेट कर सकते हैं, जबकि कॉलेज हेल्प-डेस्क स्वयंसेवक कई छात्रों को कुशलतापूर्वक मार्गदर्शन कर सकते हैं, जिससे उनका प्रभाव कई गुना बढ़ जाता है।",
    impactCaseStudy1Title: "केस स्टडी: लक्ष्मी की यात्रा",
    impactCaseStudy1Desc: "आंध्र प्रदेश के एक छोटे से गाँव की एक होनहार छात्रा लक्ष्मी को भाषा की बाधाओं और सीमित इंटरनेट पहुँच के कारण छात्रवृत्तियाँ खोजने में कठिनाई हुई। टेलीग्राम पर समर्थएआई का उपयोग करते हुए, उनके पिता ने तेलुगु में उनकी अकादमिक उपलब्धियों और वित्तीय स्थिति के बारे में बात की। कुछ ही मिनटों में, समर्थएआई ने तीन प्रासंगिक राज्य और राष्ट्रीय छात्रवृत्तियों का सुझाव दिया। लक्ष्मी ने सफलतापूर्वक एक के लिए आवेदन किया, अपनी इंजीनियरिंग की डिग्री के लिए धन सुरक्षित किया।",
    roadmapTitle: "भविष्य का रोडमैप: कल के शिक्षार्थियों के लिए नवाचार",
    roadmapIntro: "छात्रों को सशक्त बनाने की हमारी यात्रा निरंतर है। समर्थएआई लगातार विकसित हो रहा है, भविष्य के लिए रोमांचक सुविधाओं और विस्तारों की योजना है:",
    roadmapWhatsApp: "व्हाट्सएप एकीकरण",
    roadmapWhatsAppDesc: "व्हाट्सएप को शामिल करने के लिए हमारी मैसेजिंग प्लेटफ़ॉर्म उपस्थिति का विस्तार करना, सहज, चैट-आधारित छात्रवृत्ति खोज के साथ एक व्यापक दर्शकों तक पहुँचना।",
    roadmapOCR: "ओसीआर दस्तावेज़ स्कैनिंग",
    roadmapOCRDesc: "योग्यता पूर्व-जाँच के लिए एआई द्वारा प्रासंगिक जानकारी निकालने के साथ, उपयोगकर्ताओं को दस्तावेज़ स्कैन करने और अपलोड करने की अनुमति देकर आवेदन प्रक्रिया को और सरल बनाना।",
    roadmapVoiceOnly: "उन्नत वॉयस-ओनली मोड",
    roadmapVoiceOnlyDesc: "न्यूनतम दृश्य इंटरैक्शन पसंद करने वाले उपयोगकर्ताओं के लिए पूरी तरह से वॉयस-ड्रिवन अनुभव विकसित करना, जिससे प्लेटफ़ॉर्म और भी अधिक सुलभ हो सके।",
    roadmapLowBandwidth: "अनुकूलित कम-बैंडविड्थ उपयोग",
    roadmapLowBandwidthDesc: "धीमे या रुक-रुक कर चलने वाले इंटरनेट कनेक्शन पर भी समर्थएआई अत्यधिक कार्यात्मक और उत्तरदायी रहे, यह सुनिश्चित करने के लिए निरंतर सुधार, ग्रामीण उपयोगकर्ताओं के लिए महत्वपूर्ण।",
    roadmapMoreLanguages: "विस्तारित भाषा समर्थन",
    roadmapMoreLanguagesDesc: "समर्थएआई को एक व्यापक और विविध छात्र आबादी के लिए सुलभ बनाने के लिए अधिक क्षेत्रीय भारतीय भाषाओं के लिए समर्थन पेश करना।",
    contactTitle: "हमसे संपर्क करें और शामिल हों",
    contactIntro: "क्या आपके कोई प्रश्न, प्रतिक्रिया है या समर्थएआई के साथ साझेदारी करना चाहते हैं? हमें आपसे सुनकर खुशी होगी!",
    contactEmail: "हमें ईमेल करें",
    contactPartnerships: "साझेदारी और सहयोग",
    contactFeedback: "प्रतिक्रिया और समर्थन",
    contactJoinUs: "हमारे मिशन में शामिल हों",
    contactJoinUsDesc: "यदि आप सामाजिक भलाई के लिए एआई का लाभ उठाने के लिए भावुक हैं, तो हम हमेशा हमसे जुड़ने के लिए प्रतिभाशाली व्यक्तियों और संगठनों की तलाश में रहते हैं। हमसे संपर्क करें!",
    chatPlaceholder: "अपनी छात्रवृत्ति प्रश्न बोलें या टाइप करें...",
    exampleQueries: "उदाहरण प्रश्न:",
    exampleQuery1: "इंजीनियरिंग छात्रों के लिए छात्रवृत्तियाँ।",
    exampleQuery2: "कम आय वाले परिवारों से लड़कियों के लिए छात्रवृत्तियाँ।",
    exampleQuery3: "एससी/एसटी छात्रवृत्तियों के लिए पात्रता।",
    microphoneListen: "सुन रहा है...",
    microphoneTapToSpeak: "बोलने के लिए टैप करें",
    microphoneProcessing: "प्रसंस्करण...",
    scholarshipName: "योजना का नाम",
    category: "श्रेणी",
    incomeLimit: "आय सीमा",
    description: "विवरण",
    applyNow: "अभी आवेदन करें",
    loadingScholarships: "छात्रवृत्तियाँ ढूँढ रहा है...",
    noScholarshipsFound: "आपकी प्रश्न के आधार पर कोई छात्रवृत्ति नहीं मिली। कृपया पुनः वाक्यांशित करने का प्रयास करें या अधिक विवरण प्रदान करें।",
    errorOccurred: "एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    aiThinking: "समर्थएआई सोच रहा है...",
    speechRecognitionError: "भाषण पहचान त्रुटि। कृपया पुनः प्रयास करें।",
    noSpeechDetected: "कोई भाषण नहीं मिला। कृपया पुनः प्रयास करें।",
  },
};
